name: Tests

on: [push]

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download binary
        run: |
          curl -L -s https://github.com/fabpot/local-php-security-checker/releases/download/v1.2.0/local-php-security-checker_1.2.0_linux_amd64 -o local-php-security-checker
          chmod +x local-php-security-checker
      - name: Run binary
        run: ./local-php-security-checker
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install Composer dependencies
        run: composer install --no-interaction
      - name: Run PHPCS
        run: vendor/bin/phpcs
  phpunit:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: budget_testing
          MYSQL_ROOT_PASSWORD: helloworld123
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v1
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Set up .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
      - name: Install Composer dependencies
        run: composer install --no-interaction
      - name: Generate key
        run: php artisan key:generate
      - run: npm install
      - run: npm run build
      - name: Prepare database
        run: php artisan migrate --database=testing
      - name: Run PHPUnit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml
      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)
  dusk:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: budget_testing
          MYSQL_ROOT_PASSWORD: helloworld123
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v1
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Set up .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
      - name: Install Composer dependencies
        run: composer install --no-interaction
      - name: Generate key
        run: php artisan key:generate
      - run: npm install
      - run: npm run build
      - name: Prepare database
        run: php artisan migrate --database=testing
      - name: Run Dusk
        run: |
          php artisan dusk:chrome-driver --detect
          ./vendor/laravel/dusk/bin/chromedriver-linux --port=9515 &
          php artisan serve --no-reload &
          php artisan dusk
